title: "Umair Jibran"
email: umairjibran7@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Umair Jibran is a cross-platform(web and mobile) developer. He uses flutter for mobile application development, while for web development he prefers to use Embedded JavaScript(EJS). He loves NodeJS and PHP for backend functionalities.

  He has conducted different workshops and seminars. He however is currently acting as Campus lead for Microsoft Learn Program.
baseurl: "/" 
url: "https://umairjibran.github.io/" 
twitter_username: umairjibran7
github_username:  umairjibran

sass:
  sass_dir: _sass

icon: ./assets/img/icon.jpg
